name: Update gist with WakaTime stats
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: wangchi/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 35524930c9cf492062c84081aad853d2
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
